WITH sub AS (
    SELECT MEMBER_ID, COUNT(MEMBER_ID)
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) desc
    LIMIT 1
)

SELECT MEMBER_NAME, REVIEW_TEXT, date_format(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE as M 
left join REST_REVIEW as R
on M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID = (SELECT MEMBER_ID
                   FROM sub)
ORDER BY REVIEW_DATE, REVIEW_TEXT;